/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERV_H_RPCGEN
#define _SERV_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SER 0x30000003
#define VSER 1

#if defined(__STDC__) || defined(__cplusplus)
#define s1 1
extern  void * s1_1(int , CLIENT *);
extern  void * s1_1_svc(int , struct svc_req *);
#define s2 2
extern  double * s2_1(CLIENT *);
extern  double * s2_1_svc(struct svc_req *);
extern int ser_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define s1 1
extern  void * s1_1();
extern  void * s1_1_svc();
#define s2 2
extern  double * s2_1();
extern  double * s2_1_svc();
extern int ser_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERV_H_RPCGEN */
