/*	serv_server.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "serv.h"
	#include<math.h>/**/
	#include<unistd.h>/**/
	/**/static double res;
	
void *
s1_1_svc(int arg1,  struct svc_req *rqstp)
{
	static char * result;
		/**/sleep(120);
		/**/printf("Server s1 duerme 120 segundos!!!\n");
		/**/res = sqrt(arg1);	
	return (void *) &result;
}

double *
s2_1_svc(struct svc_req *rqstp)
{
	static double  result;
		/**/result = res;
		/**/printf("Server s2 asigna el resultado!!!\n");
	return &result;
}
/*	serv_server.c */
